# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Hello"
  config.vm.boot_timeout = 900  
  config.vm.define "avm" do |testvm|
    testvm.vm.box = "precise32"
    testvm.vm.boot_timeout = 900
  end
end
