#!/usr/bin/env python
from squadron import main,initialize,daemon
from argparse import ArgumentParser
import json
import os
import socket

if __name__ == "__main__":
    parser = ArgumentParser(
                description='Easy configuration management tool',
                epilog="http://gosquadron.com"
            )
    
    parser.add_argument('-i', '--directory', help='Input directory')
    parser.add_argument('-n', '--node-name', help='Override this node\'s name', default=socket.getfqdn())
    parser.add_argument('-sk', '--skeleton', help='Init with a skeleton structure (no internet access)', action='store_true') #False by default
    parser.add_argument('-git', '--gitrepro', help='Git repro to use for INIT command')
    parser.add_argument('-hub', '--hub', help='Specify a hub to register with')
    parser.add_argument('command', choices=['init','check','apply', 'daemon'], help='Which action to execute')

    args = parser.parse_args()

    if args.directory is None:
        args.directory = os.getcwd()

    if(args.command == 'init'):
        initialize.init(args.directory, args.skeleton, args.gitrepro)
        exit(0)
    
    if(args.command == 'daemon'):
        daemon.run(args.directory, args.hub, args.git)
        exit(0)

    print "{}: dir {} node_name {}".format(args.command, args.directory, args.node_name)

    main.go(args.directory, args.node_name, args.command == 'check')
